# title: Long Haul
title: Go deep
# description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
description: Go deep and be professional

# change to your URL
# url: https://long-haul.netlify.app
url: https://godeep.pro
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Articles (English)
    url: /articles
  - title: Articles (中文)
    url: /articles-zh
  - title: Articles (日本語)
    url: /articles-jp
  - title: Categories
    url: /categories
  - title: Contact
    url: /contact
  - title: About
    url: /about

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
